figure('Units', 'pixels',...
    'Position', [0 0 900 500],...
    'Color', 'white');
hold on;

err_sor = semilogy(SOR_iter, SOR_err);
err_cg = semilogy(CG_iter, CG_err);
err_cgj = semilogy(CG_jacobi_preconditioner_iter, CG_jacobi_preconditioner_err);

set(err_sor          , ...
  'LineStyle'       , ':'      , ...
  'LineWidth'       , 2        , ...
  'Marker'          , 'none'   , ...
  'Color'           , [.7 .0 .0]  );

set(err_cg         , ...
  'LineStyle'       , '-.'     , ...
  'LineWidth'       , 2        , ...
  'Marker'          , 'none'   , ...
  'Color'           , [.0 .0 .7]  );

set(err_cgj         , ...
  'LineStyle'       , '-'     , ...
  'LineWidth'       , 2        , ...
  'Marker'          , 'none'   , ...
  'Color'           , [.0 .7 .0]  );

XLabel = xlabel('Iterations');
YLabel = ylabel('|r|/|b|');

Legend = legend( ...
  [err_sor, err_cg, err_cgj]         , ...
  'SOR method'                , ...
  'Conjugate gradients',...
  'CG w/ Jacobi preconditioner');

set(gca, 'YScale', 'log')
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([XLabel, YLabel], ...
    'FontName'   , 'AvantGarde');
set([Legend, gca]             , ...
    'FontSize'   , 20           );
set([XLabel, YLabel]  , ...
    'FontSize'   , 23          );

set(gca, ...
  'Box'         , 'off'     , ...
  'Color'       , [.95 .95 .95],...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'on'      , ...
  'XMinorGrid'       , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'YMinorGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YLim'        , [1e-11,1],...
  'YTick'       , [1e-11,1e-9,1e-7,1e-5,1e-3,1e-1,1], ...
  'LineWidth'   , 1         );
