figure('Units', 'pixels',...
    'Position', [0 0 800 480],...
    'Color', 'white');
hold on;

err_jacobi = semilogy(Jacobi_iter, Jacobi_err);
err_gaussseidel = semilogy(Gaussseidel_iter, Gaussseidel_err);
err_descent = semilogy(Descent_iter, Descent_err);

set(err_jacobi          , ...
  'LineStyle'       , ':'      , ...
  'LineWidth'       , 2        , ...
  'Marker'          , 'none'   , ...
  'Color'           , [.7 .0 .0]  );

set(err_gaussseidel         , ...
  'LineStyle'       , '-.'     , ...
  'LineWidth'       , 2        , ...
  'Marker'          , 'none'   , ...
  'Color'           , [.0 .0 .7]  );

set(err_descent         , ...
  'LineStyle'       , '-'     , ...
  'LineWidth'       , 2        , ...
  'Marker'          , 'none'   , ...
  'Color'           , [.0 .7 .0]  );

XLabel = xlabel('Iterations');
YLabel = ylabel('|r|/|b|');

Legend = legend( ...
  [err_jacobi, err_gaussseidel, err_descent]         , ...
  'Jacobi method'                , ...
  'Gauss-Seidel method',...
  'Gradient descent');

set(gca, 'YScale', 'log')
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([XLabel, YLabel], ...
    'FontName'   , 'AvantGarde');
set([Legend, gca]             , ...
    'FontSize'   , 20           );
set([XLabel, YLabel]  , ...
    'FontSize'   , 23          );

set(gca, ...
  'Box'         , 'off'     , ...
  'Color'       , [.95 .95 .95],...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'on'      , ...
  'XMinorGrid'       , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'YMinorGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , [1e-9,1e-7,1e-5,1e-3,1e-1,1], ...
  'LineWidth'   , 1         );
